import Link from "next/link";
import { Button, Card } from "@/components/ui";
import { db } from "@/lib/db";

export const dynamic = "force-dynamic";
export const revalidate = 60;

export default async function Home() {
  const [members, posts, leaders, matches] = await Promise.all([
    db.user.count({ where: { active: true } }),
    db.news.findMany({ where: { status: "PUBLISHED" }, orderBy: { publishedAt: "desc" }, take: 3, select: { slug: true, title: true, excerpt: true, publishedAt: true } }),
    db.user.findMany({ where: { active: true }, orderBy: [{ points: "desc" }, { wins: "desc" }], take: 5, select: { id: true, username: true, displayName: true, points: true, wins: true, losses: true, rank: true } }),
    db.match.findMany({ where: { status: "APPROVED" }, orderBy: { playedAt: "desc" }, take: 4, include: { playerOne: true, playerTwo: true, winner: true } }),
  ]);
  const top = leaders[0];
  return <main>
    <section className="noise grid-bg scanlines border-b border-white/10">
      <div className="mx-auto grid max-w-7xl gap-12 px-5 pb-24 pt-20 lg:grid-cols-[1.15fr_.85fr] lg:items-center lg:pb-32 lg:pt-28">
        <div className="relative z-10">
          <p className="eyebrow">Roblox / Time Bomb Duels / Season 01</p>
          <h1 className="mt-5 max-w-4xl text-6xl font-black leading-[.9] tracking-[-.07em] sm:text-7xl lg:text-[7.5rem]">NO SAFE<br/><span className="text-[#ed3044]">PLAYS.</span></h1>
          <p className="mt-7 max-w-xl text-base leading-7 text-zinc-400 sm:text-lg">Bloodline is a competitive clan built for players who turn pressure into performance. Enter the roster, climb the tiers and leave a mark.</p>
          <div className="mt-8 flex flex-wrap gap-3"><Button href={process.env.NEXT_PUBLIC_DISCORD_INVITE}>Enter the clan</Button><Button href="/matches" secondary>View match log</Button></div>
          <div className="mt-12 flex flex-wrap items-center gap-x-8 gap-y-3 text-xs font-black uppercase tracking-wider text-zinc-500"><span><b className="mr-2 text-xl text-white">{members}</b> active members</span><span><b className="mr-2 text-xl text-white">{top?.points ?? 0}</b> top points</span><span><b className="mr-2 text-xl text-white">{matches.length}</b> recent verified</span></div>
        </div>
        <div className="relative mx-auto w-full max-w-md lg:max-w-none">
          <div className="absolute -right-4 -top-8 h-24 w-24 rounded-full border border-[#c8f451]/40 bg-[#c8f451]/10 blur-[1px]" />
          <Card className="glow-red relative overflow-hidden border-[#ed3044]/30 bg-[#10131a]/90 p-5 sm:p-7"><div className="flex items-center justify-between border-b border-white/10 pb-4"><span className="eyebrow !text-[#ed3044]">Live intel</span><span className="flex items-center gap-2 text-[10px] font-black uppercase tracking-widest text-[#c8f451]"><i className="h-2 w-2 rounded-full bg-[#c8f451] shadow-[0_0_12px_#c8f451]"/>Season active</span></div><div className="py-10"><div className="text-xs font-black uppercase tracking-[.25em] text-zinc-500">Current threat level</div><div className="mt-2 flex items-end gap-3"><div className="text-7xl font-black leading-none text-white">HIGH</div><div className="mb-2 text-sm font-bold text-[#ed3044]">01</div></div><div className="mt-8 grid grid-cols-5 gap-1">{["#ed3044","#ed3044","#ed3044","#c8f451","#ffffff"].map((color,index)=><span key={index} className="h-2" style={{backgroundColor:color}}/>)}</div><p className="mt-5 max-w-xs text-sm leading-6 text-zinc-400">The season is moving fast. Every verified duel changes the board.</p></div><div className="grid grid-cols-2 gap-3 border-t border-white/10 pt-4"><div><div className="text-2xl font-black">{matches.length.toString().padStart(2,"0")}</div><div className="text-[10px] font-black uppercase tracking-widest text-zinc-500">Recent matches</div></div><Link href="/rankings" className="flex items-center justify-end text-xs font-black uppercase tracking-widest text-[#c8f451]">Open board <span className="ml-2 text-lg">↗</span></Link></div></Card>
        </div>
      </div>
    </section>
    <section className="mx-auto max-w-7xl px-5 py-20 lg:py-28"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">The hierarchy</p><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Who is setting the pace?</h2></div><Link href="/rankings" className="text-sm font-black uppercase tracking-wider text-[#c8f451]">Full leaderboard ↗</Link></div><div className="mt-10 grid gap-3 lg:grid-cols-5">{leaders.map((user,index)=><Link href={`/members/${user.id}`} key={user.id} className={`group ${index===0?"lg:col-span-2":""}`}><Card className={`h-full p-5 transition group-hover:-translate-y-1 group-hover:border-[#c8f451]/50 ${index===0?"bg-[#151a23]":""}`}><div className="flex items-start justify-between"><span className={`text-4xl font-black ${index===0?"text-[#ed3044]":"text-zinc-600"}`}>{String(index+1).padStart(2,"0")}</span><span className="rounded-full border border-white/10 px-2 py-1 text-[10px] font-black uppercase tracking-widest text-zinc-500">{user.rank}</span></div><div className="mt-12 truncate text-xl font-black">{user.displayName ?? user.username}</div><div className="mt-1 text-xs text-zinc-500">@{user.username}</div><div className="mt-5 flex items-end justify-between border-t border-white/10 pt-4"><div><b className="text-2xl">{user.points}</b><span className="ml-1 text-xs text-zinc-500">PTS</span></div><span className="text-xs font-bold text-zinc-500">{user.wins}W / {user.losses}L</span></div></Card></Link>)}</div></section>
    <section className="border-y border-white/10 bg-[#0d1016]"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-[.8fr_1.2fr] lg:py-24"><div><p className="eyebrow !text-[#ed3044]">Verified activity</p><h2 className="mt-3 text-4xl font-black tracking-tight">Recent clashes.</h2><p className="mt-4 max-w-sm leading-7 text-zinc-400">No rumours. No inflated stats. Only results reviewed by the Bloodline admin team.</p><Link href="/matches" className="mt-8 inline-flex text-sm font-black uppercase tracking-wider text-[#c8f451]">See every result ↗</Link></div><div className="grid gap-2">{matches.length===0?<Card className="p-7 text-zinc-400">The first verified match will appear here.</Card>:matches.map((match,index)=><div key={match.id} className="grid grid-cols-[32px_1fr_auto] items-center gap-4 border-b border-white/10 py-4"><span className="font-black text-zinc-600">0{index+1}</span><div><div className="font-bold">{match.winner?.displayName ?? match.winner?.username} <span className="mx-2 text-xs font-normal text-zinc-600">defeated</span>{match.winner?.id===match.playerOneId?match.playerTwo.displayName??match.playerTwo.username:match.playerOne.displayName??match.playerOne.username}</div><div className="mt-1 text-xs text-zinc-500">{match.mode} · {match.playedAt.toLocaleDateString()}</div></div><span className="text-xs font-black uppercase tracking-wider text-[#c8f451]">Verified</span></div>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 lg:py-28"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Clan transmission</p><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Latest intel.</h2></div><Link href="/news" className="text-sm font-black uppercase tracking-wider text-[#c8f451]">Open newsroom ↗</Link></div><div className="mt-10 grid gap-3 md:grid-cols-3">{posts.map((post,index)=><Link href={`/news/${post.slug}`} key={post.slug}><Card className="group h-full p-6 transition hover:-translate-y-1 hover:border-[#ed3044]/50"><div className="flex items-center justify-between text-[10px] font-black uppercase tracking-widest text-zinc-500"><span>Dispatch 0{index+1}</span><span>{post.publishedAt?.toLocaleDateString()}</span></div><h3 className="mt-12 text-2xl font-black leading-tight group-hover:text-[#c8f451]">{post.title}</h3><p className="mt-4 text-sm leading-6 text-zinc-400">{post.excerpt}</p></Card></Link>)}</div></section>
    <section className="px-5 pb-20"><div className="noise mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 overflow-hidden rounded-2xl border border-[#ed3044]/30 p-8 sm:p-12 lg:flex-row lg:items-end"><div><p className="eyebrow !text-[#ed3044]">Your move</p><h2 className="mt-3 max-w-2xl text-4xl font-black tracking-tight sm:text-6xl">Pressure makes the roster.</h2></div><Button href={process.env.NEXT_PUBLIC_DISCORD_INVITE}>Join Bloodline ↗</Button></div></section>
  </main>;
}
